version: "3.8"
services:

  auth-server:
    container_name: auth-server
    restart: unless-stopped
    tty: true
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - untitledmmo
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgsql-volume:/var/lib/postgresql/data:delegated
    networks:
      - untitledmmo

volumes:
  pgsql-volume:

networks:
  untitledmmo:
    driver: bridge
