name: Docker Image CI

on:
  push:
    branches: master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-Frontend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish Auth Server
      uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/Heavenly-Dragons/auth-server:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/Heavenly-Dragons/auth-server:latest
        cache-to: type=inline
